export const highlightData = [
    {
        id: 'hj8mmCibbeg',
        title: '[KBO] LG vs 한화 5차전',
        desc: 'PS 최다 루타  타이 안타를  만들어 내며  대기록  작성하는  김현수 QS+ 피칭’ 7이닝을  1실점으로  막아낸  톨허스트!',
        img: '/images/highlight/highlight1.jpg',
        date: '11.03',
        time: '16:41',
    },
    {
        id: 'MXtRwE',
        title: '[KBL] SK vs LG',
        desc: 'SK 픽앤롤과  미드-레인지 점퍼,  공격  리바운드  가담  이후  풋백  득점 LG에 역전승  1라운드  마지막  경기에서  첫  승',
        img: '/images/highlight/highlight2.jpg',
        date: '11.02',
        time: '17:20',
    },
    {
        id: 'P1CTjxmT9is',
        title: '[UFC] 가르시아 vs 데이비드 오나마',
        desc: 'UFC 6연승 스티브 가르시아 데이비드 오나마 상대로 타격  파워! 오나마를 맞아 랭킹을 방어하고 체급 정상을 향해 나아감',
        img: '/images/highlight/highlight3.jpg',
        date: '11.02',
        time: '15:22',
    },
    {
        id: 'I2rnzDgFsWY',
        title: '[WTA] 제시카 페굴라 vs 코코 고프',
        desc: '리야드에서 열린 파이널 테니스 경기에서 미국의 제시카 페굴라가 미국의 코코 고프를 상대로 리턴을 치다 ',
        img: '/images/highlight/highlight4.jpg',
        date: '11.02',
        time: '16:26',
    },
    {
        id: 'cxnvruuWtNU',
        title: '[Lega Serie A] 밀란 vs 로마',
        desc: '주 세페 메아차에서  치뤄진  치열한  경기 밀란의  홈 어드밴티지가  승패를  나누고  로마의  훌륭한  퍼포먼스!',
        img: '/images/highlight/highlight5.jpg',
        date: '11.02',
        time: '15:42',
    },
    {
        id: 'SsRnfOWIJOI',
        title: '[NFL] Broncos vs Texans',
        desc: '휴스턴에서 행해진 NFL의 덴버 브론코스 대 휴스턴 텍산스전의 하프타임, 팀의 영예의 고리에 새롭게 합류한 멕네어의 활약',
        img: '/images/highlight/highlight6.jpg',
        date: '11.02',
        time: '10:00',
    },
];
