export const mySportsData = [
    { id: 1, nameKr: '맨 시티', nameEn: 'Man City', img: '/images/logo/manCity.svg', isLive: true },
    {
        id: 2,
        nameKr: '맨 유나이티드',
        nameEn: 'Manchester United',
        img: '/images/logo/manchesterUnited.svg',
        isLive: false,
    },
    {
        id: 3,
        nameKr: '첼시',
        nameEn: 'Chelsea',
        img: '/images/logo/manchesterUnited.svg',
        isLive: false,
    },
    {
        id: 4,
        nameKr: '뉴캐슬',
        nameEn: 'Newcastle',
        img: '/images/logo/newcastle.svg',
        isLive: false,
    },
    { id: 5, nameKr: '아스날', nameEn: 'Arsenal', img: '/images/logo/arsenal.svg', isLive: true }, // Live 예시
    {
        id: 6,
        nameKr: '바로셀로나FC',
        nameEn: 'FC Barcelona',
        img: '/images/logo/fcBarcelona.svg',
        isLive: false,
    },
    {
        id: 7,
        nameKr: '레알마드리드',
        nameEn: 'Realmadrid',
        img: '/images/logo/realmadrid.svg',
        isLive: false,
    },
    {
        id: 8,
        nameKr: '파리 생제르맹 FC',
        nameEn: 'Paris Saint Germain FC',
        img: '/images/logo/parisSaint.svg',
        isLive: false,
    },
    {
        id: 9,
        nameKr: '브랜트퍼드',
        nameEn: 'Brentford',
        img: '/images/logo/brentford.svg',
        isLive: false,
    },
    { id: 10, nameKr: '맨 티', nameEn: 'Man ity', img: '/images/logo/manCity.svg', isLive: false },
];

// 2. 리그 데이터 (예시)
export const leagueDataList = [
    {
        id: 1,
        nameKr: '프리미어 리그',
        nameEn: 'Premier League',
        img: '/images/league/01.svg',
        isLive: false,
    },
    {
        id: 2,
        nameKr: '챔피언스 리그',
        nameEn: 'Champions League',
        img: '/images/league/02.svg',
        isLive: true,
    },
    {
        id: 3,
        nameKr: '리리가 리그',
        nameEn: 'LaLiga',
        img: '/images/league/03.svg',
        isLive: false,
    },
    {
        id: 4,
        nameKr: '분데스리가 리그',
        nameEn: 'Bundesliga',
        img: '/images/league/04.svg',
        isLive: false,
    },
    {
        id: 5,
        nameKr: '리그 1',
        nameEn: 'Ligue 1',
        img: '/images/league/05.svg',
        isLive: false,
    },
    {
        id: 6,
        nameKr: '세리에 A',
        nameEn: 'Serie A',
        img: '/images/league/06.svg',
        isLive: false,
    },
    {
        id: 7,
        nameKr: '리가 포르투갈',
        nameEn: 'Liga Portugal',
        img: '/images/league/07.svg',
        isLive: false,
    },
    {
        id: 8,
        nameKr: 'K리그',
        nameEn: 'K League',
        img: '/images/league/08.svg',
        isLive: false,
    },
    {
        id: 9,
        nameKr: '에레디비시 리그',
        nameEn: 'Eredivisie',
        img: '/images/league/09.svg',
        isLive: false,
    },
    {
        id: 10,
        nameKr: '메이저리그 사커',
        nameEn: 'Major League Soccer',
        img: '/images/league/10.svg',
        isLive: false,
    },
    {
        id: 11,
        nameKr: '사우디 프로 리그',
        nameEn: 'Saudi Pro League',
        img: '/images/league/11.svg',
        isLive: false,
    },
];
